name: Compatibility

on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+']

permissions:
  contents: read

jobs:
  compatibility:
    uses: liberusoftware/.github/.github/workflows/package-compatibility.yml@main
